on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: 📦 Initialize
      run: npm ci

    - name: 🛠 Build
      run: CI= npm run build

    - name: 🧹 Lint
      run: npm run lint

    - name: ✅ Tests
      run: npm run test
