on:
  workflow_call:
    inputs:
      bucket:
        required: true
        type: string
      remote:
        type: string
        default: remoteEntry.js
      env_vars:
        description: List of environment variables to set up, given in env=value format.
        required: false
        type: string
      host_var:
        required: true
        type: string
      node_options:
        description: List of node variables to set up, given in env=value format.
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
env:
  VERSION: ${{ github.event.pull_request.number }}
  REACT_APP_ENV: staging

jobs:
  install:
    runs-on: ubuntu-latest
    name: 📦 Install & cache
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: node_modules
          key: modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            modules-
      - name: "Install dependencies"
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NODE_OPTIONS: ${{ inputs.node_options }}

  lint:
    runs-on: ubuntu-latest
    name: "🧹 Lint"
    needs: [install]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: node_modules
          key: modules-${{ hashFiles('**/package-lock.json') }}
      - name: "Lint"
        run: npm run lint
        env:
          NODE_OPTIONS: ${{ inputs.node_options }}

  test:
    runs-on: ubuntu-latest
    name: "✅ Tests"
    needs: [install]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: node_modules
          key: modules-${{ hashFiles('**/package-lock.json') }}
      - name: "Run tests"
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: node_modules
          key: modules-${{ hashFiles('**/package-lock.json') }}
      - name: Set environment variables
        if: ${{ inputs.env_vars }}
        run: |
          for i in "${{ inputs.env_vars }}"
          do
            printf "%s\n" $i >> $GITHUB_ENV
          done
      - name: "Build"
        run: PUBLIC_PATH=https://${{ inputs.bucket }}/pr/${{ env.VERSION }} GENERATE_SOURCEMAP=false CI= npm run build
        env:
          NODE_OPTIONS: ${{ inputs.node_options }}

      - name: 🚀 Upload to S3
        if: github.event.repository.name != 'compass-federation-template'
        run: |
          npx s3-deploy './build/**/${{ inputs.remote }}' --cwd './build/' --bucket ${{ inputs.bucket }}/pr/${{ env.VERSION }} --cacheControl 'max-age=300, stale-if-error=2592000' --region eu-west-1 --metadata-directive REPLACE
          npx s3-deploy './build/**/*' --cwd './build/' --bucket ${{ inputs.bucket }}/pr/${{ env.VERSION }} --cacheControl 'max-age=2592000, stale-if-error=2592000' --region eu-west-1 --metadata-directive REPLACE
          sleep 10s
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NODE_OPTIONS: ${{ inputs.node_options }}

      - name: Find PB Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ env.VERSION }}
          comment-author: "github-actions[bot]"
          body-includes: |
            :woman_scientist: We've  created a preview branch for you! Check your code here:

      - name: Create or update PB comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ env.VERSION }}
          body: |
            :woman_scientist: We've  created a preview branch for you! Check your code here: [https://hub.marfeel.com?env=${{ inputs.host_var }},https://${{ inputs.bucket }}/pr/${{ env.VERSION }}/static/js](https://hub.marfeel.com?env=${{ inputs.host_var }},https://${{ inputs.bucket }}/pr/${{ env.VERSION }}/static/js)
          reactions: rocket
          edit-mode: replace
