on:
  workflow_call:
    inputs:
      env_vars:
        description: List of environment variables to set up, given in env=value format.
        required: false
        type: string


jobs:
  install:
    runs-on: ubuntu-latest
    name: 📦 Install & cache
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            modules-
      - name: 'Install dependencies'
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    name: '🧹 Lint'
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: modules-${{ hashFiles('**/package-lock.json') }}
      - name: 'Lint'
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    name: '✅ Tests'
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: modules-${{ hashFiles('**/package-lock.json') }}
      - name: 'Run tests'
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: modules-${{ hashFiles('**/package-lock.json') }}
      - name: Set environment variables
        if: ${{ inputs.env_vars }}
        run: |
          for i in "${{ inputs.env_vars }}"
          do
            printf "%s\n" $i >> $GITHUB_ENV
          done
      - name: 'Build'
        run: CI= npm run build
