on:
  workflow_call:
    inputs:
      publicPath:
        required: true
        type: string
      bucket:
        required: true
        type: string
      remote:
        type: string
        default: remoteEntry.js
      env_vars:
        description: List of environment variables to set up, given in env=value format.
        required: false
        type: string
      node_options:
        description: List of node variables to set up, given in env=value format.
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      FASTLY_KEY:
        required: true
      FASTLY_SERVICE:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ inputs.bucket }}
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Set environment variables
        if: ${{ inputs.env_vars }}
        run: |
          for i in "${{ inputs.env_vars }}"
          do
            printf "%s\n" $i >> $GITHUB_ENV
          done

      - name: 📦 Initialize
        run: npm ci
        env:
          NODE_OPTIONS: ${{ inputs.node_options }}

      - name: 🛠 Build
        run: PUBLIC_PATH=${{ inputs.publicPath }}/v2 GENERATE_SOURCEMAP=false CI= npm run build
        env:
          NODE_OPTIONS: ${{ inputs.node_options }}

      - name: 🚀 Upload to S3
        if: github.event.repository.name != 'compass-federation-template'
        run: |
          npx s3-deploy './build/**/${{ inputs.remote }}' --cwd './build/' --bucket ${{ inputs.bucket }}/v2 --cacheControl 'max-age=300, s-maxage=2592000' --region eu-west-1
          npx s3-deploy './build/**/*' --cwd './build/' --bucket ${{ inputs.bucket }}/v2 --cacheControl 'max-age=2592000' --region eu-west-1
          aws s3api wait object-exists --bucket ${{ inputs.bucket }} --key v2/${{ inputs.remote }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 🚽 Purge Fastly
        if: github.event.repository.name != 'compass-federation-template'
        uses: Marfeel/github-actions/common/actions/purgeFastly@master
        with:
          fastly-key: ${{ secrets.FASTLY_KEY }}
          service-id: ${{ secrets.FASTLY_SERVICE }}
